name: Sanity Check

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for cml to comment

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest
        id: pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q --junitxml report.xml

      - name: Report results with CML
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment --repo $GITHUB_REPOSITORY --pull-request ${{ github.event.pull_request.number }} --summary report.xml
